import os

BROKER_URL = os.getenv('REDISCLOUD_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDISCLOUD_URL', 'redis://localhost:6379/0')
CELERY_RESULT_ENGINE_OPTIONS = { 'echo': True }
CELERY_IGNORE_RESULT = True
CELERY_SEND_EVENTS = True
CELERY_TASK_RESULT_EXPIRES = 60
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']


